Refactor mod initialization and uninstall

diff --git a/.shell/S00init b/.shell/S00init
--- a/.shell/S00init
+++ b/.shell/S00init
@@ -11,60 +11,128 @@ MOD=/data/.mod/.zmod
 
 set -x
 
-fix_config() {
-    echo "START fix_config"
-    date
-    
-    TMP_CFG_PATH=/tmp/printer.tmp.cfg
-    
-    # Create dump with parameters from printer.base.cfg
-    chroot $MOD /bin/python3 /root/printer_data/scripts/cfg_backup.py \
-    --mode backup \
-    --config /opt/config/printer.base.cfg \
-    --data $TMP_CFG_PATH \
-    --params /opt/config/mod/.cfg/init.move.cfg
-    
-    # If any parameters found
-    if [ $? -eq 0 ]; then
-        # TODO: Merge with defaults?
-        DATA_MOVE_CFG=$TMP_CFG_PATH
-    else
-        DATA_MOVE_CFG=/opt/config/mod/.cfg/data.init.move.cfg
+mount_data_partition() {
+    # mount data - this would otherwise be mounted later by flashforge
+    if ! mount | grep -q /dev/mmcblk0p7; then
+        echo "Mounting /data partition..."
+        fsck -y /dev/mmcblk0p7 || true
+        mount /dev/mmcblk0p7 /data;
     fi
     
-    # Move params from printer.base.cfg to printer.cfg
-    chroot $MOD /bin/python3 /root/printer_data/scripts/cfg_backup.py \
-    --mode restore --avoid_writes \
-    --config /opt/config/printer.cfg \
-    --data $DATA_MOVE_CFG \
-    --params /opt/config/mod/.cfg/init.move.cfg
+    # local timeout=60
+    # while ! mount | grep -q /dev/mmcblk0p7 && [ $timeout -gt 0 ]; do
+    #     echo "Waiting /data..."; sleep 1;
+    #     timeout=$(( timeout - 1 ))
+    # done
     
-    # Initialize display configuration
-    /opt/config/mod/.shell/commands/zdisplay.sh init
+    if ! mount | grep -q /dev/mmcblk0p7; then
+        echo "Mounting /data failed."
+        exit 1
+    fi
+}
+
+handle_special_boot_mode() {
+    if [ -f /opt/config/mod/SKIP_ZMOD ]; then
+        echo "Skipping mod load"
+        
+        md -p /data/lost+found
+        mount --bind /data/lost+found /data/.mod
+        rm -f /opt/config/mod/SKIP_ZMOD
+
+        exit 0
+    elif [ -f /opt/config/mod/REMOVE ]; then
+        echo "Removing mod..."
+        
+        mount_data_partition
+
+        cp -f /opt/config/mod_data/.shell/uninstall.sh /opt/uninstall.sh
+        /opt/config/mod_data/.shell/uninstall.sh
+        
+        exit 0
+    elif [ -f /opt/config/mod/SOFT_REMOVE ]; then
+        echo "Removing mod in soft mode..."
+        
+        mount_data_partition
+        cp -f /opt/config/mod_data/.shell/uninstall.sh /opt/uninstall.sh
+        /opt/uninstall.sh --soft
+        
+        exit 0
+    fi
+}
+
+initialize() {
+    echo "*** Start initialization"
     
-    # Init printer.base.cfg configuration
-    chroot $MOD /bin/python3 /root/printer_data/scripts/cfg_backup.py \
-    --mode restore --avoid_writes \
-    --config /opt/config/printer.base.cfg \
-    --params /opt/config/mod/.cfg/init.base.cfg \
-    --data /opt/config/mod/.cfg/data.init.base.cfg
+    handle_special_boot_mode
     
-    # Restore printer.base.cfg if changed since backup
-    if [ -f /opt/config/printer.base.cfg.bak ]; then
-        chroot $MOD /bin/python3 /root/printer_data/scripts/cfg_backup.py \
-        --mode restore --avoid_writes \
-        --config /opt/config/printer.base.cfg \
-        --params /opt/config/mod_data/backup.params.cfg \
-        --data /opt/config/printer.base.cfg.bak
+    # If we are here: mod loading not skipped
+    mount_data_partition
+    
+    mount --bind /opt/config/mod_data/.shell/scripts /root/printer_data/scripts
+    
+    mkdir -p /opt/config/mod_data/log/
+    
+    init_chroot
+    apply_klipper_patches
+    fix_config
+    
+    # oh-my-zsh
+    mkdir -p /root/.oh-my-zsh
+    mount --bind /opt/config/mod/.zsh/.oh-my-zsh /root/.oh-my-zsh
+    ln -s /opt/config/mod/.zsh/.profile /root/.profile
+    ln -s /opt/config/mod/.zsh/.zshrc /root/.zshrc
+    
+    # version
+    GIT_BRANCH=$(chroot $MOD git --git-dir=/opt/config/mod/.git rev-parse --abbrev-ref HEAD)
+    GIT_COMMIT_ID=$(chroot $MOD git --git-dir=/opt/config/mod/.git rev-parse --short HEAD)
+    GIT_COMMIT_DATE=$(chroot $MOD git --git-dir=/opt/config/mod/.git show -s HEAD --format=%cd --date=format:'%d.%m.%Y %H:%M:%S')
+    
+    FIRMWARE_VERSION=$(cat /root/version)
+    MOD_VERSION=$(cat /opt/config/mod/version.txt)
+    PATCH_VERSION="$GIT_BRANCH-$GIT_COMMIT_ID @ $GIT_COMMIT_DATE"
+    
+    chroot $MOD /opt/config/mod/.root/version.sh "$FIRMWARE_VERSION" "$MOD_VERSION" "$PATCH_VERSION"
+    
+    # database
+    if [ -f "/opt/config/mod_data/database/moonraker-sql.db" ]; then
+        /opt/config/mod/.shell/migrate_db.sh
     fi
     
+    # misc
+    /opt/config/mod/.shell/motd.sh > /etc/motd
+    /opt/config/mod/.shell/commands/zshaper.sh --clear
+
     # (?) Restrict public unauthorized access to printer's camera (only SerialNnumber is needed)
     grep -q qvs.qiniuapi.com /etc/hosts || sed -i '2 i\127.0.0.1 qvs.qiniuapi.com' /etc/hosts
     
     # TODO: remove modified variable files ?
     grep -q ZLOAD_VARIABLE /opt/klipper/klippy/extras/save_variables.py || cp /opt/config/mod/.shell/save_variables.py /opt/klipper/klippy/extras/save_variables.py
     
-    echo "END fix_config"
+    echo "*** End initialization"
+}
+
+init_chroot() {
+    mount -t proc /proc $MOD/proc
+    mount --rbind /sys $MOD/sys
+    mount --rbind /dev $MOD/dev
+    
+    mount --bind /tmp $MOD/tmp
+    
+    mkdir -p $MOD/opt/config
+    mount --bind /opt/config $MOD/opt/config
+    
+    mkdir -p $MOD/data
+    mount --bind /data $MOD/data
+    
+    mount --bind /opt/klipper $MOD/opt/klipper
+    
+    mkdir -p $MOD/root/printer_data/misc
+    mkdir -p $MOD/root/printer_data/tmp
+    mkdir -p $MOD/root/printer_data/comms
+    mkdir -p $MOD/root/printer_data/certs
+    
+    # moon
+    ln -fs /opt/config/mod/.root/moonraker $MOD/root/moonraker-env/moonraker
 }
 
 apply_klipper_patches() {
@@ -98,23 +166,57 @@ apply_klipper_patches() {
     done
 }
 
-#mount --bind /opt/config/mod_data/.shell/scripts /root/printer_data/scripts
+fix_config() {
+    TMP_CFG_PATH=/tmp/printer.tmp.cfg
+    
+    # Create dump with parameters from printer.base.cfg
+    chroot $MOD /bin/python3 /root/printer_data/scripts/cfg_backup.py \
+        --mode backup \
+        --config /opt/config/printer.base.cfg \
+        --data $TMP_CFG_PATH \
+        --params /opt/config/mod/.cfg/init.move.cfg
+    
+    # If any parameters found
+    if [ $? -eq 0 ]; then
+        # TODO: Merge with defaults?
+        DATA_MOVE_CFG=$TMP_CFG_PATH
+    else
+        DATA_MOVE_CFG=/opt/config/mod/.cfg/data.init.move.cfg
+    fi
+    
+    # Move params from printer.base.cfg to printer.cfg
+    chroot $MOD /bin/python3 /root/printer_data/scripts/cfg_backup.py \
+        --mode restore --avoid_writes \
+        --config /opt/config/printer.cfg \
+        --data $DATA_MOVE_CFG \
+        --params /opt/config/mod/.cfg/init.move.cfg
+        
+    # Initialize display configuration
+    /opt/config/mod/.shell/commands/zdisplay.sh init
+    
+    # Init printer.base.cfg configuration
+    chroot $MOD /bin/python3 /root/printer_data/scripts/cfg_backup.py \
+        --mode restore --avoid_writes \
+        --config /opt/config/printer.base.cfg \
+        --params /opt/config/mod/.cfg/init.base.cfg \
+        --data /opt/config/mod/.cfg/data.init.base.cfg
+    
+    # Restore printer.base.cfg if changed since backup
+    if [ -f /opt/config/printer.base.cfg.bak ]; then
+        chroot $MOD /bin/python3 /root/printer_data/scripts/cfg_backup.py \
+            --mode restore --avoid_writes \
+            --config /opt/config/printer.base.cfg \
+            --params /opt/config/mod_data/backup.params.cfg \
+            --data /opt/config/printer.base.cfg.bak
+    fi
+}
 
-apply_klipper_patches
+mv /opt/config/mod_data/log/init.log.4 /opt/config/mod_data/log/init.log.5
+mv /opt/config/mod_data/log/init.log.3 /opt/config/mod_data/log/init.log.4
+mv /opt/config/mod_data/log/init.log.2 /opt/config/mod_data/log/init.log.3
+mv /opt/config/mod_data/log/init.log.1 /opt/config/mod_data/log/init.log.2
+mv /opt/config/mod_data/log/init.log /opt/config/mod_data/log/init.log.1
 
-mkdir -p /opt/config/mod_data/log/
-
-mv /opt/config/mod_data/log/fix_config.log.4 /opt/config/mod_data/log/fix_config.log.5
-mv /opt/config/mod_data/log/fix_config.log.3 /opt/config/mod_data/log/fix_config.log.4
-mv /opt/config/mod_data/log/fix_config.log.2 /opt/config/mod_data/log/fix_config.log.3
-mv /opt/config/mod_data/log/fix_config.log.1 /opt/config/mod_data/log/fix_config.log.2
-mv /opt/config/mod_data/log/fix_config.log /opt/config/mod_data/log/fix_config.log.1
-
-apply_klipper_patches
-
-# Motd
-/opt/config/mod/.shell/motd.sh > /etc/motd
-
-fix_config &>/opt/config/mod_data/log/fix_config.log
+initialize &>/opt/config/mod_data/log/init.log
 
 sync
